package:
  name: pytorch-scatter
  version: 2.1.0

source:
  path: ../..

requirements:
  build:
    - {{ compiler('c') }}  # [win]

  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install .
  script_env:
    - FORCE_CUDA
    - TORCH_CUDA_ARCH_LIST

test:
  imports:
    - torch_scatter

about:
  home: https://github.com/rusty1s/pytorch_scatter
  license: MIT
  summary: PyTorch Extension Library of Optimized Scatter Operations
